let userScore = 0;
let compScore = 0;

const choices = document.querySelectorAll(".choice");
const msg = document.querySelector ("#msg");
const userScorePara = document.querySelector("#user-score");
const compScorePara = document.querySelector("#comp-score");

//Random index/option generated by the computer
const genCompChoice = () => {
    //rock, paper, scissors
    const options = ["rock", "paper", "scissors"];
    const randIdx = Math.floor(Math.random() * 3);
    return options[randIdx];
};

//draw game function
const drawGame = () => {
    // console.log("Game was draw");
    msg.innerText = `Game was Draw! Play Again.`
    msg.style.backgroundColor = "#081b31";
}

//Function to show who will win or lose
const showWinner = (userWin, userChoice, compChoice) => {
    if (userWin) {
        userScore++; //score update
        userScorePara.innerText = userScore;
        // console.log("You Win!");
        msg.innerText = `You Win! Your ${userChoice} beats ${compChoice}` ; //msg update
        msg.style.backgroundColor = "green";
    }
    else {
        compScore++; //score update
        compScorePara.innerText = compScore;
        // console.log("You Lose");
        msg.innerText = `You Lose! ${compChoice} beats your ${userChoice}`; //msg update
        msg.style.backgroundColor = "red";
    }
}

//Computer choice
const playGame = (userChoice) => {  //our system what is the userchoice so we passed it as a parameter
    // console.log("userChoice is ", userChoice);
    const compChoice = genCompChoice();
    // console.log("computer choice is ", compChoice);

    if (userChoice === compChoice) {
        //draw game 
        drawGame();
    }
    else {
        let userWin = true; //Conditions for winner
        if (userChoice === "rock") {
            //scissors, paper
            userWin = compChoice === "scissors" ? true : false;
        }
        else if (userChoice === "paper"){
            //rock, scissors
            userWin = compChoice === "scissors" ? false : true;
        }
        else {
            //rock, paper
            userWin = compChoice === "rock" ? false : true;
        }
        showWinner(userWin, userChoice, compChoice);
    }
};

//User Choice
choices.forEach((choice) => {
    // console.log(choice);
    choice.addEventListener("click", () => {
        const userChoice = choice.getAttribute("id");
        // console.log("choice was clicked", choiceId);
        playGame(userChoice);
    });
});